Add genre to product
josef-kudlacek/eshop-backend pull request #3
Opened 2024-12-19 20:38 UTC by josef-kudlacek

2024-12-27 16:31 UTC, Marvel-IT commented on src/main/java/cz/jkdabing/backend/controller/ProductGenreController.java
> +    public ResponseEntity<MessageResponse> addAuthorToProduct(@Valid @RequestBody ProductGenreDTO productGenreDTO) {
Proč je název metody "addAuthorToProduct"? Zřejmě se jedná o žánr produktu.

2024-12-27 16:33 UTC, Marvel-IT commented on src/main/java/cz/jkdabing/backend/controller/ProductGenreController.java
> +    public ResponseEntity<MessageResponse> deleteAuthorFromProduct(@PathVariable long genreId) {
Proč je název metody "deleteAuthorFromProduct"? Jedná se zřejmě o žánr 🤔

2024-12-27 17:25 UTC, Marvel-IT requested changes
Mrkni na názvy metod v kontroleru ;-)

2024-12-29 20:39 UTC, josef-kudlacek commented
> Mrkni na názvy metod v kontroleru ;-)

@Marvel-IT: Dobrý postřeh. Upravil jsem a dal znovu na code review. Odebrání žánru z produktu jsem přejmenoval na remove. i když se ve vazební tabulce bude vazba mazat, reálně dochází k pouze k odebrání žánru z produktu, ale ne k mazání samotného žánru.

2024-12-29 21:22 UTC, josef-kudlacek commented
Úpravy na základě code review jsem otestoval skrze Postman.
Vše OK.

2024-12-29 21:44 UTC, closed without merging

2024-12-29 22:32 UTC, josef-kudlacek commented
@TomasKrucky @Marvel-IT 
Trošku se mi rozsypali pull requesty po tom, co jsem zkoušel přejmenovat branche. Dával jsem tam číslování, abych se pak líp vyznal v pořadí, ve kterém se budou dávat na pull request a ve kterém se můžou mergovat.

Nicméně výtky jsem upravil a zamergoval do master větve v rámci #6 PR.